kind: Secret
apiVersion: v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  selfLink: /api/v1/namespaces/fiap-lab4chain-rm342579/secrets/sample-database
  resourceVersion: '54430693'
  name: sample-database
  uid: f53e4888-0694-447f-b514-6ce4d2b00d82
  creationTimestamp: '2022-04-07T01:23:35Z'
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2022-04-07T01:23:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:database-name': {}
          'f:database-password': {}
          'f:database-user': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
            'f:template.openshift.io/expose-database_name': {}
            'f:template.openshift.io/expose-password': {}
            'f:template.openshift.io/expose-username': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:template': {}
        'f:type': {}
  namespace: fiap-lab4chain-rm342579
  labels:
    app: sample-database
    app.kubernetes.io/component: sample-database
    app.kubernetes.io/instance: sample-database
    template: postgresql-persistent-template
data:
  database-name: c2FtcGxlZGI=
  database-password: c2FtcGxlZGI=
  database-user: c2FtcGxlZGI=
type: Opaque
